AIESEC-in-Japan/aiesecjp-web

components/Footer.vue

#18 フッター
フッターの作成
- components/Footer.vueにミニサイトマップを追加
- デザインの崩れなどないか

ミニサイトマップの追加

---

components/Header.vue

<h2>Issue</h2>
<p>#21 ヘッダー</p>
<h2>概要</h2>
<p>ヘッダーコンポーネントを編集する</p>
<h2>変更内容</h2>
<h2>レビューポイント</h2>
<p>白戸さんのモックのとおりになっているか</p>

feature header

---

components/AboutAiesec.vue

#16 ABOUT AIESEC
- About Aiesecのページを作成しました。
- ComponentsにAboutAiesec.vueを作成して、Index.vueに追加しました。
- 説明会に行くのボタンにかぶってしまっています。そこを解消したいです。
- ハクトさんの写真通りになっているか

feature About Aiesec

---

components/OurPrograms.vue
pages/index.vue

#26 Top/OurProgramsコンポーネントの作成
Our Programsコンポーネントの作成
- components/にOurPrograms.vueを作成
- pages/index.vueでコンポーネントの呼び出し
- モックの通り作成できているか
- 画像のサイズ感など

Add OurPrograms

---

components/IcxTopcomponent.vue
pages/icx/index.vue
yarn.lock

28
ICXトップコンポーネントを作成
ICXトップコンポーネントを作りました。
見て欲しいところは全部なのですが、
・ロゴや文章の余白のバランス
・classの付け方
を特に見て欲しいです。

feature IcxTopcomponent

---

components/Header.vue

#63 
リンクをクリックして他のページに移れるようにする
ヘッダーの三つのリンクを書き換え
リンク先を正しく指定できてるかどうか

fix the header link

---

components/top/OurPrograms.vue

なし
おそらく未完成だと思われるので、UI部分を作っていきます
とりあえずとりあえずこんな感じ
サイズとかわからなかったので適当です。
- タイトルが黒くなっているのは意図的なのか、間違えているのかわからないので変えてません
- リンク先もわからなかったので何も入れてないです
- サイズ系記載なかったのでそれっぽく作っただけです。
- スマホ対応は別途必要

TOPページOur programs作成

---

components/top/OurPartners.vue

[TOP] Our Partnersのデザイン修正 #121
アイコンの大きさなど微妙に差異があったので修正

[TOP] Our Partnersのデザイン修正 

---

assets/scss/_base.scss
components/incoming/AboutIcxIntern.vue
pages/incoming/index.vue

[ICX] アイセックのインターンシップの受け入れ部分のコンポーネントの作成 #29
ないので作りました。
- セクションの大きさが個々で設定されていますが、そんな必要ないと思うので、baseで定義して揃えたいです。

[ICX] アイセックのインターンシップの受け入れ部分

---

components/top/AboutAiesec.vue

[TOP] About AIESEC のデザイン修正 #119
デザインが微妙に異なっていたので修正
- デザインの修正
- scssの使い方がわかりにくいので構造化

[TOP] About AIESEC のデザイン修正

---

README.md

環境構築手順の整備 #1
新しくJOINした人がすぐに開発環境を整えることができるように。
わかりやすいか

開発環境はこのプロジェクトについての説明を書きます

---

assets/scss/_variable.scss
components/base/Footer.vue
components/base/Header.vue
components/global-youth-dialogue/Top.vue
pages/global-youth-dialogue/index.vue
pages/incoming/index.vue

[Global Youth Dialogue]Top作成 #215
[Global Youth Dialogue]Top作成 します。
色も追加

[Global Youth Dialogue]Top

---

components/base/CommonColor.js
components/base/RoundButton.vue
components/global-youth-dialogue/Detail.vue
components/global-youth-dialogue/apply.vue
pages/global-youth-dialogue/index.vue

[Global Youth Dialogue]案内を追加 #217
公式LINEや参加方法を追加

[Global Youth Dialogue]案内

---

components/global-youth-dialogue/Voice.vue
components/global-youth-dialogue/apply.vue
pages/global-youth-dialogue/index.vue

[Global Youth Dialogue] 参加者の声はこちらを追加 #219

[Global Youth Dialogue] 参加者の声はこちら

---

components/base/RoundButton.vue
components/global-youth-dialogue/FixedFooter.vue
components/global-youth-dialogue/Voice.vue
components/global-youth-dialogue/apply.vue
pages/global-youth-dialogue/index.vue

[Global Youth Dialogue]　公式LINEへのリンクの固定footerを追加 #218

[Global Youth Dialogue]　公式LINEへのリンクの固定footer

---

assets/scss/_variable.scss
components/Incoming/AboutIntern.vue
components/Incoming/CorporationInternship.vue
components/Incoming/CorporationMerit.vue
components/Incoming/Detail.vue
components/Incoming/Top.vue
components/top/MainView.vue

[RWD対応] ICXの対応 #232
RWD対応
SP表示に対応
spanの使い方が間違っていたので修正

[RWD対応] ICXの対応 

---

components/privacy-policy/PolicyTop.vue

[RWD対応] 個人情報 #233
個人情報をSPに対応
タイトル部分のみ変なところで改行されないように調整した。
長い文章の場合は画面幅によっても変わってしまうので、調整したところで意味ないです。

[RWD対応] 個人情報

---

components/Outgoing/Program.vue

[OGX]不要なリンク削除「詳しくみる」 #193
BOTくん等がちゃんと働いているか見るためのPRです。

[OGX]不要なリンク削除

---

components/Outgoing/Detail.vue
components/safety/Descriptions.vue
components/safety/Top.vue

[RWD対応] 安全への取り組み 

---

assets/scss/_carousel.scss
components/safety/Committee.vue
components/top/WhyWhat.vue
components/top/carouselContent/3rd.vue
pages/safety/index.vue

[安全への取り組み]安全管理委員会の議事録を載せる #237

[安全への取り組み]安全管理委員会の議事録を載せる

---

components/base/Header.vue

#246 
最新のdevelopを取り込んだ
アイコンがdrawerを開いている際に close アイコンになっている
（同一ブランチで最新のdevelopを取り込む方法がわからなかったので
別ブランチでpushしてます。そこも間違いあったら指摘ください）

ドロワーのアイコン表示を修正

---

components/global-youth-dialogue/FixedFooter.vue
plugins/windowSize.js

[refactor] process.browser の排除 #273
非推奨になっていたメソットを置き換え。
今回はmount時に何かするとかはないので、hooksは使用しない

[refactor] process.browser の排除 

---

assets/scss/_table.scss
components/about/CustomTable.vue

about usのcssのpxをremに変更しました

---

components/top/OurPrograms.vue

修正「Global Youth Dialogue」→「global youth dialogue」
#281 
プロダクト正式表記（全て小文字）への修正

【誤字修正】global youth dialogueの表記

---

components/global-youth-dialogue/Top.vue

追加知らない国に、知っている人ができ「た」ら、
#281 
dialogueトップページの誤字修正

【誤字修正】global youth dialogueのトップページ

---

components/global-youth-dialogue/Detail.vue

誤字修正 「様々ない会話」→「様々な会話」
#281 
誤字の修正

【誤字修正】global youth dialogue

---

components/about/OfficerList.vue

理事の先生の方の名前変更

---

components/about/AdvisorList.vue

後でIssue作ります汗
AboutUsの部分で変更があったのでしました。
諮問 田中伸男（公共財団法人笹川平和財団 会長）
→諮問田中伸男（タナカグローバル（株） CEO）
鈴木良伸（有限会社ステージ・フォー・ワン 代表取締役）
→鈴木美伸
ミスってないか見て欲しいです。

誤字修正、役職修正しました

---

.gitignore
.idea/.gitignore
README.md
static/README.md

close #341
リリース方法についての記述や、数日前に追加したLPについての記述を追加しました。
- 記述は必要十分か
- 他に書いてほしいものはあるか

staticの概要とリリースについての記述を追加

---

static/lp/recruit2022/index.html

Reverts AIESEC-in-Japan/aiesecjp-web#347
masterのバージョンを戻します

Revert "google tag manager 適用コードの設置"

---

static/lp/recruit2022/index.html

Reverts AIESEC-in-Japan/aiesecjp-web#351

Revert "Google Tag Manager の設置に関して、release ブランチを切る"

---

components/about/OfficerList.vue

ページ内容の更新
専務理事、常務理事の更新
理事の所属の更新
誤字脱字がないか
ページに正しく反映されているか

aboutページの文章を更新

---

components/global-youth-dialogue/Top.vue
static/lp/recruit2022/index.html

global youth dialogue の会期を5月のものに更新
新歓LP の入会フローを更新
会期を「申し込み締め切り：5/18　開催日時：5/27~5/31」に変更
新歓LP の入会フローから「step 01 AJ全体説明会」を削除
これに伴い、以下の step をスライド
補足説明の「全体説明会」→「委員会活動説明会」
誤字脱字
取り除いたコードにミスがないか

Update GYD Peak ＆ LP 入会フロー

---

components/base/Header.vue
nuxt.config.js

headerに直接タグ付け

---

components/base/Header.vue
nuxt.config.js

Reverts AIESEC-in-Japan/aiesecjp-web#395

Revert "headerに直接タグ付け"

---

nuxt.config.js
pages/global-youth-dialogue/index.vue

gydページへのga紐づけ
gydページのindex.vueに個別headを定義しました
構文は正しいか
IDついてるか
デプロイが通るか

customize gyd_head

---

pages/global-youth-dialogue/index.vue

add analytics tag

---

components/global-youth-dialogue/Top.vue

gyd開催日時を削除

---

components/press/2021.vue

press 上のテキストを中央揃えに変更
press/2021.vue の article / section 各々に、
display: flex; 等をあてました
プレビューで表示が整っているかどうか

press 注記の中央揃え

---

components/global-youth-dialogue/Apply.vue
components/global-youth-dialogue/FixedFooter.vue

gyd 公式ライン開設に伴う、HP 記載の LINE 登録リンクの変更
global-youth-dialogue/Apply.vue 及び global-youth-dialogue/FixedFooter.vue の data( ) 内、ButtonProps の url を置き換え  
差分

upd_line_link

---

static/lp/recruit2023/index.html

md lp/recruit2023 header

---

components/base/Header.vue

update: recruitリンクの更新

---

components/press/2022.vue

アニュアルレポートのURLを修正

---

components/press/2022.vue

urlの全角部を修正

---

components/about/FinanceInfo.stories.js
components/about/FinanceInfo.vue
pages/about/index.vue

add 財務情報の追加

---

components/about/Donation.stories.js
components/about/Donation.vue
pages/about/index.vue

add: AboutUsページに寄付金のセクションを追加（暫定）

---

components/base/RoundButton.vue

fix: gydページのボタンクリックをGoogleアナリティクスで計測できるようタグを変更 button→a

---

components/base/RoundButton.vue
components/global-youth-dialogue/Apply.vue
components/global-youth-dialogue/FixedFooter.vue

fix: ボタンコンポーネントのURLの記述方法を変更（プロパティ→hrefで直接記述）

---

components/global-youth-dialogue/Apply.vue
components/global-youth-dialogue/FixedFooter.vue
components/global-youth-dialogue/Voice.vue

gydページ公式LINEURLの変更（GYD公式LINE→AJ公式LINE）

update: gydページ公式LINEURLの変更（GYD公式LINE→AJ公式LINE）

---

components/global-youth-dialogue/Detail.vue

fix: 会期の詳細説明の変更　（4人グループ→グループ）

---

components/about/FinanceInfo.vue
components/safety/Committee.vue

- 団体情報ページ：活動計算書・貸借対照表の追加
- 安全への取り組みページ：令和六年度第一回海外安全管理委員会開催報告の追加

Feature/add safety&finance info

---

nuxt.config.js

update: GA4

---

assets/json/news.json
components/news/NewsList/News0003.vue
components/top/MainView.vue
pages/news/0003/index.vue

add: ニュースの追加とレイアウトの修正

---

nuxt.config.js
pages/about/index.vue
pages/annual-report/index.vue
pages/contact/alumni/index.vue
pages/contact/company/index.vue
pages/contact/student/index.vue
pages/donation/index.vue
pages/download/completed/index.vue
pages/download/index.vue
pages/for-company/index.vue
pages/incoming/index.vue
pages/index.vue
pages/message/index.vue
pages/news/0001/index.vue
pages/news/index.vue
pages/organization/index.vue
pages/outgoing/index.vue
pages/privacy-policy/index.vue
pages/safety/index.vue
pages/site-policy/index.vue

meta: ページタイトルとサイトタイトル/説明の追加
